alter table "public"."team_members" drop constraint "team_members_pkey";

drop index if exists "public"."team_members_pkey";

alter table "public"."team_members" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX team_members_pkey ON public.team_members USING btree (id);

alter table "public"."team_members" add constraint "team_members_pkey" PRIMARY KEY using index "team_members_pkey";



