create table "public"."team_members" (
    "user_id" uuid not null,
    "team_id" bigint
);


alter table "public"."team_members" enable row level security;

create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "game_id" bigint
);


alter table "public"."teams" enable row level security;

create table "public"."user_data" (
    "user_id" uuid not null,
    "tournaments_participated_in" integer not null default 0,
    "tournaments_won" integer not null default 0
);


alter table "public"."user_data" enable row level security;

CREATE UNIQUE INDEX team_members_pkey ON public.team_members USING btree (user_id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX user_data_pkey ON public.user_data USING btree (user_id);

alter table "public"."team_members" add constraint "team_members_pkey" PRIMARY KEY using index "team_members_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."user_data" add constraint "user_data_pkey" PRIMARY KEY using index "user_data_pkey";

alter table "public"."team_members" add constraint "team_members_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."team_members" validate constraint "team_members_team_id_fkey";

alter table "public"."team_members" add constraint "team_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."team_members" validate constraint "team_members_user_id_fkey";

alter table "public"."teams" add constraint "teams_game_id_fkey" FOREIGN KEY (game_id) REFERENCES games(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."teams" validate constraint "teams_game_id_fkey";

alter table "public"."user_data" add constraint "user_data_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."user_data" validate constraint "user_data_user_id_fkey";

grant delete on table "public"."team_members" to "anon";

grant insert on table "public"."team_members" to "anon";

grant references on table "public"."team_members" to "anon";

grant select on table "public"."team_members" to "anon";

grant trigger on table "public"."team_members" to "anon";

grant truncate on table "public"."team_members" to "anon";

grant update on table "public"."team_members" to "anon";

grant delete on table "public"."team_members" to "authenticated";

grant insert on table "public"."team_members" to "authenticated";

grant references on table "public"."team_members" to "authenticated";

grant select on table "public"."team_members" to "authenticated";

grant trigger on table "public"."team_members" to "authenticated";

grant truncate on table "public"."team_members" to "authenticated";

grant update on table "public"."team_members" to "authenticated";

grant delete on table "public"."team_members" to "service_role";

grant insert on table "public"."team_members" to "service_role";

grant references on table "public"."team_members" to "service_role";

grant select on table "public"."team_members" to "service_role";

grant trigger on table "public"."team_members" to "service_role";

grant truncate on table "public"."team_members" to "service_role";

grant update on table "public"."team_members" to "service_role";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";

grant delete on table "public"."user_data" to "anon";

grant insert on table "public"."user_data" to "anon";

grant references on table "public"."user_data" to "anon";

grant select on table "public"."user_data" to "anon";

grant trigger on table "public"."user_data" to "anon";

grant truncate on table "public"."user_data" to "anon";

grant update on table "public"."user_data" to "anon";

grant delete on table "public"."user_data" to "authenticated";

grant insert on table "public"."user_data" to "authenticated";

grant references on table "public"."user_data" to "authenticated";

grant select on table "public"."user_data" to "authenticated";

grant trigger on table "public"."user_data" to "authenticated";

grant truncate on table "public"."user_data" to "authenticated";

grant update on table "public"."user_data" to "authenticated";

grant delete on table "public"."user_data" to "service_role";

grant insert on table "public"."user_data" to "service_role";

grant references on table "public"."user_data" to "service_role";

grant select on table "public"."user_data" to "service_role";

grant trigger on table "public"."user_data" to "service_role";

grant truncate on table "public"."user_data" to "service_role";

grant update on table "public"."user_data" to "service_role";

create policy "Enable read access for all users"
on "public"."team_members"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."teams"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."user_data"
as permissive
for select
to public
using (true);




